USE NBNREPORTING
GO

SELECT
  COUNT(OCCURRENCE_KEY) AS COUNT,
  DES.STATUS_KIND AS STATUS
INTO
  #NBNREPORTING_TEMP
FROM
  WEALDEN_ALL A
LEFT OUTER JOIN
  NBNData.dbo.VW_DESIGNATIONS DES ON
  A.LIST_ITEM_KEY COLLATE Latin1_General_CI_AI = DES.TAXON_LIST_ITEM_KEY
WHERE
  A.[Taxon Group] IS NOT NULL AND
  A.[SAMPLE_VAGUE_DATE_TYPE] != 'U'
GROUP BY 
  DES.STATUS_KIND
GO

SELECT
  [COUNT],
  STATUS
FROM
  #NBNREPORTING_TEMP
WHERE
  STATUS IS NOT NULL
ORDER BY
  STATUS
GO

DROP TABLE #NBNREPORTING_TEMP
GO
