SELECT
  ITN.*,
  TLI.TAXON_LIST_ITEM_KEY,
  TXG.TAXON_GROUP_NAME
FROM
  TAXON_GROUP AS TXG
INNER JOIN
  TAXON_VERSION AS TXV ON
  TXG.TAXON_GROUP_KEY = TXV.OUTPUT_GROUP_KEY
INNER JOIN
  TAXON_LIST_ITEM AS TLI ON
  TXV.TAXON_VERSION_KEY = TLI.TAXON_VERSION_KEY
INNER JOIN
  INDEX_TAXON_NAME AS ITN ON
  TLI.TAXON_LIST_ITEM_KEY = TLI.TAXON_LIST_ITEM_KEY
WHERE
  TXG.TAXON_GROUP_NAME = 'bird' AND
  ITN.SORT_ORDER = '10600000000'