USE bigreport
GO
select  LEFT(OCCURRENCE_KEY,8) AS CUSTODIAN,
        OCCURRENCE_KEY,
        SAMPLE_KEY,
        CAST([RECOMMENDED TAXON SORT ORDER] AS BIGINT) AS SORT_ORDER,
        CASE WHEN [TAXON COMMON NAME] = [TAXON LATIN NAME] THEN
          'A ' + [TAXON GROUP]
        ELSE
          [TAXON COMMON NAME]
        END AS [COMMON NAME],
        [TAXON LATIN NAME],
        [TAXON GROUP],
        REPLACE([SAMPLE_SPATIAL_REF], ' ', '') AS GRID_REF,
        LEN(REPLACE([SAMPLE_SPATIAL_REF], ' ', '')) AS GR_LEN,
        CASE WHEN [SAMPLE LOCATION NAME] IS NOT NULL THEN
          CASE WHEN [SAMPLE LOCATION NAME] != [SAMPLE LOCATION] THEN
            [SAMPLE LOCATION NAME] + ', ' + [SAMPLE LOCATION]
          ELSE
            [SAMPLE LOCATION]
          END
        ELSE
          [SAMPLE LOCATION]
        END AS LOCATION,
        [SAMPLE RECORDERS],
        SAMPLE_VAGUE_DATE_START,
        SAMPLE_VAGUE_DATE_END,
        NBNData.dbo.LCReturnVagueDateShort(SAMPLE_VAGUE_DATE_START, Sample_Vague_Date_End, Sample_Vague_Date_Type) AS DATE,
        NBNData.dbo.ufn_RtfToPlaintext([OBS COMMENT]) AS [Comment] 
FROM    OBSERVATIONS
WHERE   CAST([RECOMMENDED TAXON SORT ORDER] AS BIGINT) <= 2500000000 AND
        [TAXON GROUP] IS NOT NULL AND
        LEFT(OCCURRENCE_KEY,8) != 'THU00002'
        --[occurrence_key] like 'SR000049%'
ORDER BY SORT_ORDER