use NBNData;

select top 1000
	itn2.TAXON_LIST_ITEM_KEY as RECOMMENDED_TAXON_LIST_ITEM_KEY
	,itn2.PREFERRED_NAME
	,itn2.COMMON_NAME
	,txg.TAXON_GROUP_NAME
	,itn2.SORT_ORDER
	,[COUNT] = count(itn2.TAXON_LIST_ITEM_KEY)
from
	INDEX_TAXON_NAME as itn
inner join
	INDEX_TAXON_NAME itn2 on
	itn.RECOMMENDED_TAXON_LIST_ITEM_KEY = itn2.TAXON_LIST_ITEM_KEY
inner join
	TAXON_DETERMINATION txd on
	itn.TAXON_LIST_ITEM_KEY = txd.TAXON_LIST_ITEM_KEY
inner join
	DETERMINATION_TYPE dt on
	txd.DETERMINATION_TYPE_KEY = dt.DETERMINATION_TYPE_KEY
inner join
	TAXON_OCCURRENCE txo on
	txd.TAXON_OCCURRENCE_KEY = txo.TAXON_OCCURRENCE_KEY
inner join
	VW_TAXON_GROUP txg on
	itn2.TAXON_LIST_ITEM_KEY = txg.TAXON_LIST_ITEM_KEY
where
	txd.PREFERRED = 1 and
	dt.Verified != 1 and
	txo.CHECKED = 1 and
	txo.CONFIDENTIAL != 1
group by 
	itn2.TAXON_LIST_ITEM_KEY
	,itn2.PREFERRED_NAME
	,itn2.COMMON_NAME
	,itn2.SORT_ORDER
	,txg.TAXON_GROUP_NAME
order by
	--itn2.SORT_ORDER asc
	count(itn2.TAXON_LIST_ITEM_KEY) desc



