USE NBNREPORTING
GO

SELECT
  MIN(CASE WHEN [TAXON COMMON NAME] = [TAXON LATIN NAME] THEN
    HW.[TAXON GROUP]
  ELSE
    [TAXON COMMON NAME]
  END) AS [COMMON NAME],
  [TAXON LATIN NAME],
  HW.[TAXON GROUP],
  MIN(SAMPLE_VAGUE_DATE_START) AS [FIRST RECORDED],
  MAX(SAMPLE_VAGUE_DATE_END) AS [LAST RECORDED],
  COUNT(OCCURRENCE_KEY) AS COUNT,
  [RECOMMENDED TAXON SORT ORDER],
  MIN(HW.LIST_ITEM_KEY) AS [LIST ITEM KEY],
  DES.[STATUS KIND] AS STATUS
INTO
  #HW_TEMP
FROM
  HW_ALL HW
INNER JOIN
  NBNData.dbo.VW_DESIGNATIONS DES ON
  HW.LIST_ITEM_KEY COLLATE Latin1_General_CI_AI = DES.TAXON_LIST_ITEM_KEY
WHERE
  HW.[TAXON GROUP] IS NOT NULL AND
  HW.[TAXON GROUP] != 'bird' AND
  HW.[SAMPLE_VAGUE_DATE_TYPE] != 'U' AND
  DES.[STATUS KIND] = 'WCAct'
GROUP BY 
  [TAXON LATIN NAME], HW.[TAXON GROUP], [RECOMMENDED TAXON SORT ORDER], DES.[STATUS KIND]
ORDER BY
  [RECOMMENDED TAXON SORT ORDER]
GO

SELECT
  [LIST ITEM KEY],
  [COMMON NAME],
  [TAXON LATIN NAME],
  [TAXON GROUP],
  NBNData.dbo.LCReturnDateShort([FIRST RECORDED],'D','F') AS [FIRST RECORDED],
  NBNData.dbo.LCReturnDateShort([LAST RECORDED], 'D', 'F') AS [LAST RECORDED],
  [COUNT],
  STATUS
FROM
  #HW_TEMP
GO

DROP TABLE #HW_TEMP
GO
