SELECT	dbo.FormatIndividual(I.TITLE, I.INITIALS, I.FORENAME, I.SURNAME) AS RECORDER,
		COUNT(TXO.TAXON_OCCURRENCE_KEY) AS 'No of Records'

FROM	SAMPLE AS S
		INNER JOIN	SURVEY_EVENT SE
			ON S.SURVEY_EVENT_KEY = SE.SURVEY_EVENT_KEY
			AND SE.ENTRY_DATE > dbo.LCToRataDie('01/01/2006')
			AND SE.ENTRY_DATE < dbo.LCToRataDie('31/06/2006')
		INNER JOIN SURVEY_EVENT_RECORDER SER
			ON SE.SURVEY_EVENT_KEY = SER.SURVEY_EVENT_KEY
		INNER JOIN NAME N
			ON SER.NAME_KEY = N.NAME_KEY
		INNER JOIN INDIVIDUAL I
			ON N.NAME_KEY = I.NAME_KEY
		
		INNER JOIN TAXON_OCCURRENCE TXO
			ON S.SAMPLE_KEY = TXO.SAMPLE_KEY

GROUP BY dbo.FormatIndividual(I.TITLE, I.INITIALS, I.FORENAME, I.SURNAME)

ORDER BY 'No of Records' DESC