USE NBNData
GO

DECLARE @year char(4)
SET @year = '2008'

SELECT DISTINCT --TOP 5000
	 TXO.TAXON_OCCURRENCE_KEY
	,S.ITEM_NAME AS SURVEY
	,SA.ENTRY_DATE AS SAMPLE_ENTRY
	,SA.CHANGED_DATE AS SAMPLE_CHANGED
	,TXO.CHANGED_DATE AS OBS_CHANGED
	,ITN2.PREFERRED_NAME
	,CASE WHEN ITN2.PREFERRED_NAME = ITN2.COMMON_NAME THEN
		'-'
	ELSE
		ITN2.COMMON_NAME
	END AS [COMMON NAME]
	,TXG.TAXON_GROUP_NAME AS TAXON_GROUP
	,ITN2.SORT_ORDER
	,dbo.LCReturnVagueDateShort(SE.VAGUE_DATE_START, SE.VAGUE_DATE_END, SE.VAGUE_DATE_TYPE) AS DATE
	,SE.VAGUE_DATE_START
	,SE.VAGUE_DATE_END
	,SE.VAGUE_DATE_TYPE
	,REPLACE(SA.SPATIAL_REF, ' ', '') AS SPATIAL_REF
	,LEN(REPLACE(SA.SPATIAL_REF, ' ', '')) AS SPATIAL_PRECISION
	,dbo.FormatLocation(sa.sample_key) AS LOCATION
	,dbo.FormatEventRecorders(SA.SAMPLE_KEY) AS RECORDERS
	,CASE WHEN dbo.LCAbundanceCount(TXO.TAXON_OCCURRENCE_KEY) != 0 THEN
		dbo.LCAbundanceCount(TXO.TAXON_OCCURRENCE_KEY)
	ELSE
		NULL
	END AS SUM_OF_ABUNDANCE
	,dbo.LCFormatAbundanceData(TXO.TAXON_OCCURRENCE_KEY) AS ABUNDANCES
	,dbo.ufn_RtfToPlaintext(CAST(TXO.COMMENT AS VARCHAR(MAX))) AS COMMENT
	,dbo.LCReturnEastings_c(REPLACE(SA.SPATIAL_REF, ' ', ''), SA.SPATIAL_REF_SYSTEM) AS X
	,dbo.LCReturnNorthings_c(REPLACE(SA.SPATIAL_REF, ' ', ''), SA.SPATIAL_REF_SYSTEM) AS Y
FROM
	INDEX_TAXON_NAME ITN
INNER JOIN
	INDEX_TAXON_NAME ITN2 ON
	ITN.RECOMMENDED_TAXON_LIST_ITEM_KEY = ITN2.TAXON_LIST_ITEM_KEY
INNER JOIN
	TAXON_LIST_ITEM TLI ON
	ITN.TAXON_LIST_ITEM_KEY = TLI.TAXON_LIST_ITEM_KEY
INNER JOIN
	TAXON_VERSION TXV ON
	TLI.TAXON_VERSION_KEY = TXV.TAXON_VERSION_KEY
INNER JOIN
	TAXON_GROUP TXG ON
	TXV.OUTPUT_GROUP_KEY = TXG.TAXON_GROUP_KEY
INNER JOIN
	TAXON_DETERMINATION TXD ON
	ITN.TAXON_LIST_ITEM_KEY = TXD.TAXON_LIST_ITEM_KEY
INNER JOIN
	TAXON_OCCURRENCE TXO ON
	TXD.TAXON_OCCURRENCE_KEY = TXO.TAXON_OCCURRENCE_KEY
INNER JOIN
	SAMPLE SA ON
	TXO.SAMPLE_KEY = SA.SAMPLE_KEY
INNER JOIN
	SURVEY_EVENT SE ON
	SA.SURVEY_EVENT_KEY = SE.SURVEY_EVENT_KEY
INNER JOIN
	LOCATION_NAME LN ON
	SE.LOCATION_KEY = LN.LOCATION_KEY
INNER JOIN
	TAXON_OCCURRENCE_DATA TXOD ON
	TXO.TAXON_OCCURRENCE_KEY = TXOD.TAXON_OCCURRENCE_KEY
INNER JOIN
	SURVEY S ON
	SE.SURVEY_KEY = S.SURVEY_KEY
WHERE
	TXO.ZERO_ABUNDANCE = 0
	AND TXO.CHECKED = 1
	AND	TXD.PREFERRED = 1
	AND	LN.PREFERRED = 1
	AND TXG.TAXON_GROUP_KEY = 'NHMSYS0000080054'
	AND (
		dbo.LCReturnVagueDateShort(SE.VAGUE_DATE_START, SE.VAGUE_DATE_END, SE.VAGUE_DATE_TYPE) LIKE '%'+@year+'%'
		OR (
			YEAR(SA.ENTRY_DATE) = @year
			OR YEAR(SA.CHANGED_DATE)  = @year
			OR YEAR(TXO.ENTRY_DATE)   = @year
			OR YEAR(TXO.CHANGED_DATE) = @year
		)
	)
	AND (S.ITEM_NAME NOT LIKE 'Mapmate%' AND S.ITEM_NAME NOT LIKE '%SBRS (Sussex Botanical Recording Society)%')
	
ORDER BY
	ITN2.SORT_ORDER ASC
GO
