SELECT        SA.SAMPLE_KEY,
              COMMON_NAME,
              PREFERRED_NAME,
              TXG.TAXON_GROUP_NAME,
              dbo.FormatEventRecorders(SA.SAMPLE_KEY),
              dbo.LCReturnVagueDateShort(SA.VAGUE_DATE_START,SA.VAGUE_DATE_END,SA.VAGUE_DATE_TYPE) AS SAMPLE_DATE,
              dbo.LCReturnVagueDateShort(TXD.VAGUE_DATE_START,TXD.VAGUE_DATE_END,TXD.VAGUE_DATE_TYPE) AS TXD_DATE,
              SA.VAGUE_DATE_START, SA.VAGUE_DATE_END, TXD.VAGUE_DATE_START, TXD.VAGUE_DATE_END,
              SA.VAGUE_DATE_TYPE, TXD.VAGUE_DATE_TYPE
FROM          INDEX_TAXON_NAME ITN
INNER JOIN    TAXON_DETERMINATION TXD ON
              ITN.TAXON_LIST_ITEM_KEY = TXD.TAXON_LIST_ITEM_KEY
INNER JOIN    TAXON_OCCURRENCE TXO ON
              TXD.TAXON_OCCURRENCE_KEY = TXO.TAXON_OCCURRENCE_KEY
INNER JOIN    SAMPLE SA ON
              TXO.SAMPLE_KEY = SA.SAMPLE_KEY
INNER JOIN    VW_TAXON_GROUP TXG ON
              ITN.TAXON_LIST_ITEM_KEY = TXG.TAXON_LIST_ITEM_KEY
WHERE         (SA.VAGUE_DATE_START + SA.VAGUE_DATE_END) > (TXD.VAGUE_DATE_START + TXD.VAGUE_DATE_END)
AND           TXG.TAXON_GROUP_NAME = 'insect - dragonfly (Odonata)'
