-- QUERY TO RETURN THE TAXON GROUP OF A TAXON LIST ITEM.

USE NBNDATA
GO

SELECT 
  TLI.TAXON_LIST_ITEM_KEY,
  TXG.TAXON_GROUP_NAME
FROM
  TAXON_GROUP TXG
INNER JOIN
  TAXON_VERSION TXV ON
  TXG.TAXON_GROUP_KEY = TXV.OUTPUT_GROUP_KEY
INNER JOIN
  TAXON_LIST_ITEM TLI ON
  TXV.TAXON_VERSION_KEY = TLI.TAXON_VERSION_KEY
