USE NBNData
GO

SELECT
  COUNT(TXD.TAXON_OCCURRENCE_KEY) [COUNT],
  ITN2.TAXON_LIST_ITEM_KEY,
  TXG.TAXON_GROUP_NAME
INTO #TEMP_COUNT
FROM
  INDEX_TAXON_NAME ITN
INNER JOIN
  INDEX_TAXON_NAME ITN2 ON
  ITN.RECOMMENDED_TAXON_LIST_ITEM_KEY = ITN2.TAXON_LIST_ITEM_KEY
INNER JOIN
  TAXON_DETERMINATION TXD ON
  ITN.TAXON_LIST_ITEM_KEY = TXD.TAXON_LIST_ITEM_KEY
INNER JOIN
  TAXON_OCCURRENCE TXO ON
  TXD.TAXON_OCCURRENCE_KEY = TXO.TAXON_OCCURRENCE_KEY
INNER JOIN
  VW_TAXON_GROUP TXG ON
  ITN.TAXON_LIST_ITEM_KEY = TXG.TAXON_LIST_ITEM_KEY
WHERE
  TXD.PREFERRED = 'True' AND
  TXO.CHECKED = 'True' AND
  TXO.CONFIDENTIAL = 'False' AND
  TXO.ZERO_ABUNDANCE = 'False'
GROUP BY
  ITN2.TAXON_LIST_ITEM_KEY,
  TXG.TAXON_GROUP_NAME
GO

WITH TBL AS (
  SELECT
    [COUNT],
    TAXON_LIST_ITEM_KEY,
    TAXON_GROUP_NAME,
    ROW_NUMBER() OVER(PARTITION BY TAXON_GROUP_NAME ORDER BY [COUNT] DESC) AS RESULT
  FROM #TEMP_COUNT
)
SELECT DISTINCT
  TBL.[COUNT],
  ITN.COMMON_NAME,
  ITN.PREFERRED_NAME,
  TBL.TAXON_GROUP_NAME,
  ITN.SORT_ORDER
FROM
  TBL
INNER JOIN
  INDEX_TAXON_NAME ITN ON
  TBL.TAXON_LIST_ITEM_KEY = ITN.TAXON_LIST_ITEM_KEY
WHERE
  TBL.RESULT BETWEEN 1 AND 3
ORDER BY
  ITN.SORT_ORDER
GO

DROP TABLE #TEMP_COUNT
