/*
	Get RSI species.
	Requires VW_DESIGNATIONS view
	Returns list of RSI designated species 
*/

IF object_id('tempdb..#DESIG_TEMP') IS NOT NULL
BEGIN
   DROP TABLE #DESIG_TEMP
END

USE NBNData
GO

SELECT DISTINCT
  ITN2.TAXON_LIST_ITEM_KEY,
  ITN2.PREFERRED_NAME,
  CASE
  WHEN ITN2.PREFERRED_NAME = ITN2.COMMON_NAME THEN
    TXG.TAXON_GROUP_NAME
  ELSE
    ITN2.COMMON_NAME
  END AS [COM_NAME],
  TXG.TAXON_GROUP_NAME,
  DES.STATUS_KIND,
  DES.SHORT_NAME,
  TXF.TAXON_FACT_KEY,
  ITN2.SORT_ORDER
INTO
  #DESIG_TEMP
FROM
  INDEX_TAXON_NAME ITN
INNER JOIN
  INDEX_TAXON_NAME ITN2 ON
  ITN.RECOMMENDED_TAXON_LIST_ITEM_KEY = ITN2.TAXON_LIST_ITEM_KEY
INNER JOIN
  dbo.VW_DESIGNATIONS DES ON -- Join the designations view
  ITN.TAXON_LIST_ITEM_KEY = DES.TAXON_LIST_ITEM_KEY
INNER JOIN
  VW_TAXON_GROUP TXG ON
  ITN.TAXON_LIST_ITEM_KEY = TXG.TAXON_LIST_ITEM_KEY
INNER JOIN
  TAXON_LIST_ITEM TXLI ON
  ITN.TAXON_LIST_ITEM_KEY = TXLI.TAXON_LIST_ITEM_KEY
LEFT JOIN
  TAXON_FACT TXF ON
  TXLI.TAXON_VERSION_KEY = TXF.TAXON_VERSION_KEY
WHERE
  DES.STATUS_KIND LIKE '%RSI%' 
AND ITN.RECOMMENDED_TAXON_LIST_ITEM_KEY = ITN2.RECOMMENDED_TAXON_LIST_ITEM_KEY
AND (TXF.TITLE = 'SxBRC Facts' OR TXF.TITLE IS NULL)
GO

--SELECT
--	D.TAXON_LIST_ITEM_KEY
--	,PREFERRED_NAME
--	,TXF.TITLE
--	,TXF.DATA
--FROM
--	#DESIG_TEMP D
--LEFT JOIN
--	NBNData.dbo.TAXON_FACT TXF ON
--	D.TAXON_FACT_KEY = TXF.TAXON_FACT_KEY
--ORDER BY
--	SORT_ORDER
--GO

SELECT
	D.TAXON_LIST_ITEM_KEY
	,PREFERRED_NAME
	,D.COM_NAME
	,D.TAXON_GROUP_NAME
	,D.STATUS_KIND
	,MAX(TXF.TITLE) AS TITLE
	,MAX(CAST(TXF.DATA AS VARCHAR(MAX))) AS COMMENT
	,D.SORT_ORDER
FROM
	#DESIG_TEMP D
LEFT JOIN
	NBNData.dbo.TAXON_FACT TXF ON
	D.TAXON_FACT_KEY = TXF.TAXON_FACT_KEY
GROUP BY
	D.TAXON_LIST_ITEM_KEY
	,PREFERRED_NAME
	,D.COM_NAME
	,D.STATUS_KIND
	,D.SORT_ORDER
	,D.TAXON_GROUP_NAME
ORDER BY
	SORT_ORDER
GO

DROP TABLE #DESIG_TEMP
GO
