-- Remove the CR&LFs from taxon facts
-- Show the relevant results

USE NBNREPORTING
GO

IF OBJECT_ID('NBNREPORTING..TAXON_FACT', 'U') IS NOT NULL
DROP TABLE NBNREPORTING..TAXON_FACT

SELECT * INTO TAXON_FACT FROM NBNDATA.DBO.TAXON_FACT
WHERE RIGHT(CAST(DATA AS VARCHAR(8000)), 2) = (CHAR(13)+CHAR(10))

UPDATE TAXON_FACT
SET DATA = RTRIM(SUBSTRING(DATA,1,(LEN(CAST(DATA AS VARCHAR(8000)))-2)))
GO

SELECT TAXON_FACT_KEY, RIGHT(CAST(DATA AS VARCHAR(8000)),5) FROM TAXON_FACT
GO




