USE NBNREPORTING
GO

DECLARE @FACT_KEY VARCHAR(16), @DATA BINARY(16), @ORIG_DATA VARCHAR(MAX)

DECLARE C1 CURSOR FOR
SELECT     TFB.TAXON_FACT_KEY,
           TEXTPTR(TFB.DATA), -- TARGET DATA POINTER
           TF.DATA            -- ORIGINAL DATA
FROM       TAXON_FACT_BACKUP TFB
INNER JOIN TAXON_FACT TF ON
           TFB.TAXON_FACT_KEY = TF.TAXON_FACT_KEY

OPEN C1

FETCH NEXT FROM C1
INTO @FACT_KEY, @DATA, @ORIG_DATA

WHILE @@FETCH_STATUS = 0
BEGIN

  WRITETEXT TAXON_FACT_BACKUP.DATA @DATA @ORIG_DATA

  FETCH NEXT FROM C1
  INTO @FACT_KEY, @DATA, @ORIG_DATA
END

CLOSE C1
DEALLOCATE C1
