USE [NBNData]
GO

/****** Object:  View [dbo].[VW_TAXON_GROUP]    Script Date: 13/02/2014 12:35:47 ******/
DROP VIEW [dbo].[VW_TAXON_GROUP]
GO

/****** Object:  View [dbo].[VW_TAXON_GROUP]    Script Date: 13/02/2014 12:35:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_TAXON_GROUP]
WITH SCHEMABINDING
AS
SELECT     TLI.TAXON_LIST_ITEM_KEY, TXG.TAXON_GROUP_NAME, TXG.SORT_ORDER
FROM         dbo.TAXON_GROUP AS TXG INNER JOIN
                      dbo.TAXON_VERSION AS TXV ON TXG.TAXON_GROUP_KEY = TXV.OUTPUT_GROUP_KEY INNER JOIN
                      dbo.TAXON_LIST_ITEM AS TLI ON TXV.TAXON_VERSION_KEY = TLI.TAXON_VERSION_KEY

GO
