USE NBNData
GO
SELECT
            TXO.TAXON_OCCURRENCE_KEY,
            TXO.CONFIDENTIAL,
            ITN.COMMON_NAME,
            TXG.TAXON_GROUP_NAME,
            dbo.LCReturnDateShort(SA.VAGUE_DATE_START,SA.VAGUE_DATE_END,'F') AS [DATE],
            dbo.LCReturnDateShort(SA.VAGUE_DATE_START,SA.VAGUE_DATE_END,'M') AS [MONTH],
            SA.ENTRY_DATE,
            TXO.SURVEYORS_REF,
            TXO.COMMENT
FROM        INDEX_TAXON_NAME ITN
INNER JOIN  TAXON_DETERMINATION TXD ON
            ITN.TAXON_LIST_ITEM_KEY = TXD.TAXON_LIST_ITEM_KEY
INNER JOIN  TAXON_OCCURRENCE TXO ON
            TXD.TAXON_OCCURRENCE_KEY = TXO.TAXON_OCCURRENCE_KEY
INNER JOIN  SAMPLE SA ON
            TXO.SAMPLE_KEY = SA.SAMPLE_KEY
INNER JOIN  VW_TAXON_GROUP TXG ON
            TXG.TAXON_LIST_ITEM_KEY = ITN.TAXON_LIST_ITEM_KEY
WHERE       TXG.TAXON_GROUP_NAME = 'BIRD'
AND		    TXO.CONFIDENTIAL = 1
AND			TXO.COMMENT LIKE '%This record has been marked as confidential in line with SOS agreement%'
ORDER BY ITN.COMMON_NAME ASC
GO