USE NBNData;
SELECT DISTINCT
  itn.common_name,
  itn.preferred_name,
  TL.ITEM_NAME
FROM
  INDEX_TAXON_NAME AS ITN
INNER JOIN
  VW_TAXON_GROUP AS TXG ON
  ITN.TAXON_LIST_ITEM_KEY = TXG.TAXON_LIST_ITEM_KEY
INNER JOIN
  TAXON_LIST_VERSION AS TLV ON
  ITN.TAXON_LIST_VERSION_KEY = TLV.TAXON_LIST_VERSION_KEY
INNER JOIN
  TAXON_LIST AS TL ON
  TLV.TAXON_LIST_KEY = TL.TAXON_LIST_KEY
WHERE
 TXG.TAXON_GROUP_NAME = 'BIRD' AND
 itn.preferred_name = 'Tachybaptus ruficollis'
