SELECT
  TXO.TAXON_OCCURRENCE_KEY,
  SA.VAGUE_DATE_START,
  SA.VAGUE_DATE_END,
  SE.VAGUE_DATE_START,
  SE.VAGUE_DATE_END,
  SA.VAGUE_DATE_TYPE,
  dbo.LCReturnVagueDateShort(SA.VAGUE_DATE_START, SA.VAGUE_DATE_END, SA.VAGUE_DATE_TYPE) AS DATE,
  ITN.COMMON_NAME,
  TXG.TAXON_GROUP_NAME
FROM 
  [SAMPLE] AS SA
INNER JOIN
  TAXON_OCCURRENCE AS TXO ON
  SA.SAMPLE_KEY = TXO.SAMPLE_KEY
INNER JOIN
  TAXON_DETERMINATION AS TXD ON
  TXO.TAXON_OCCURRENCE_KEY = TXD.TAXON_OCCURRENCE_KEY
INNER JOIN
  INDEX_TAXON_NAME AS ITN ON
  TXD.TAXON_LIST_ITEM_KEY = ITN.TAXON_LIST_ITEM_KEY
INNER JOIN
  VW_TAXON_GROUP AS TXG ON
  ITN.TAXON_LIST_ITEM_KEY = TXG.TAXON_LIST_ITEM_KEY
INNER JOIN
  SURVEY_EVENT AS SE ON
  SA.SURVEY_EVENT_KEY = SE.SURVEY_EVENT_KEY
WHERE
  --TXO.TAXON_OCCURRENCE_KEY = 'THU000020000009D'
  TXG.TAXON_GROUP_NAME LIKE '%ODONATA%' AND
  --LEFT(dbo.LCReturnVagueDateShort(SA.VAGUE_DATE_START, SA.VAGUE_DATE_END, SA.VAGUE_DATE_TYPE),4) = '1868'
  SA.VAGUE_DATE_START = 0
  