/**
 *
 * Remove RSI Flags
 *
**/

USE NBNData
GO

DECLARE @intErrorCode INT

BEGIN TRAN

	SELECT TAXON_OCCURRENCE_DATA.DATA, INDEX_TAXON_NAME.COMMON_NAME
	/*UPDATE 
	  TAXON_OCCURRENCE_DATA
	SET
	  TAXON_OCCURRENCE_DATA.DATA = 'NO'*/
	FROM 
	  INDEX_TAXON_NAME 
	INNER JOIN 
	  TAXON_DETERMINATION ON INDEX_TAXON_NAME.TAXON_LIST_ITEM_KEY = TAXON_DETERMINATION.TAXON_LIST_ITEM_KEY
	INNER JOIN 
	  TAXON_OCCURRENCE ON TAXON_DETERMINATION.TAXON_OCCURRENCE_KEY = TAXON_OCCURRENCE.TAXON_OCCURRENCE_KEY
	INNER JOIN 
	  TAXON_OCCURRENCE_DATA ON TAXON_OCCURRENCE.TAXON_OCCURRENCE_KEY = TAXON_OCCURRENCE_DATA.TAXON_OCCURRENCE_KEY
	INNER JOIN 
	  INDEX_TAXON_NAME AS INDEX_TAXON_NAME_1 ON INDEX_TAXON_NAME.RECOMMENDED_TAXON_LIST_ITEM_KEY = INDEX_TAXON_NAME_1.TAXON_LIST_ITEM_KEY
	WHERE 
	  (TAXON_OCCURRENCE_DATA.DATA='YES')
	AND
	  (TAXON_OCCURRENCE_DATA.MEASUREMENT_QUALIFIER_KEY='THU00002000000A8')
	AND
	  (INDEX_TAXON_NAME_1.PREFERRED_NAME='Sorex araneus');

	SELECT @intErrorCode = @@ERROR
    IF (@intErrorCode <> 0) GOTO PROBLEM

COMMIT TRAN

PROBLEM:
IF (@intErrorCode <> 0) BEGIN
PRINT 'Unexpected error occurred!'
    ROLLBACK TRAN
END
