use nbndata
go

IF object_ID('NBNReporting.dbo.locations') IS NOT NULL
	DROP TABLE NBNReporting.dbo.locations

SELECT 
  FID = IDENTITY(int,1,1),
  L.LOCATION_KEY,
  LN.ITEM_NAME,
  L.SPATIAL_REF,
  L.LAT, L.LONG,
  L.PARENT_KEY,
  AA.ITEM_NAME
INTO NBNReporting.dbo.locations
FROM 
  LOCATION L
INNER JOIN
  LOCATION_NAME LN ON
  L.LOCATION_KEY = LN.LOCATION_KEY AND
  LN.PREFERRED = 'True'
INNER JOIN
  LOCATION_ADMIN_AREAS LAA ON
  L.LOCATION_KEY = LLA.LOCATION_KEY
INNER JOIN
  ADMIN_AREAS AA ON
  LAA.ADMIN_AREA_KEY = AA.ADMIN_AREA_KEY  
GO

USE NBNReporting
ALTER TABLE locations
ADD PRIMARY KEY (FID)
GO