USE NBNDATA
GO

IF object_ID('NBNReporting.dbo.locations_without_admin_areas') IS NOT NULL
	DROP TABLE NBNReporting.dbo.locations_without_admin_areas
GO

SELECT
  FID = IDENTITY(int,1,1),
  L.LOCATION_KEY,
  LN.ITEM_NAME,
  L.LAT, L.LONG,
  LAA.LOCATION_ADMIN_AREAS_KEY
INTO NBNReporting.dbo.locations_without_admin_areas
FROM
  LOCATION L
INNER JOIN
  LOCATION_NAME LN ON
  L.LOCATION_KEY = LN.LOCATION_KEY
LEFT OUTER JOIN
  LOCATION_ADMIN_AREAS LAA ON
  L.LOCATION_KEY = LAA.LOCATION_KEY
WHERE 
  LOCATION_ADMIN_AREAS_KEY IS NULL