SELECT [RecordKey]
      ,[TaxonVersionKey]
      ,[SurveyKey]
      ,[SampleKey]
      ,[StartDate]
      ,[EndDate]
      ,[DateType]
      ,[GridReference]
      ,[Projection]
      ,[Precision]
      ,[X]
      ,[Y]
      ,[Sensitive]
      ,[ZeroAbundance]
      ,[SiteKey]
      ,[SiteName]
      ,[SampleMethod]
      ,[Recorder]
      ,[Determiner]
      ,[Abundance]
      ,[Comment]
  FROM [NBNReporting].[dbo].[ALL_NBN_clipped]
GO


